#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose

main(_) ->
    code:load_abs("render_nif.erl"),
    [render_char(C) || C <- "AZijlp"].

render_char(Char) ->
    io:format("Rendering ~p~n", [Char]),
    {Bin, Width, Height, Top} = render_nif:render(1, [Char]),
    io:format("~p: w = ~p, h = ~p, t = ~p~n", [[Char], Width, Height, Top]),
    file:write_file([Char | ".bin"], Bin).
