#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose

main(_) ->
    code:load_abs("render_nif.erl"),
    {Bin, Width, Height} = render_nif:render(2, "ij"),
    %Bin = render_nif:render(4, "Same"),
    %io:format("Bin: ~p~nSize: ~p~n", [Bin, size(Bin)]),
    io:format("Width: ~p, Height: ~p~n", [Width, Height]),
    file:write_file("text.bin", Bin).
